# Site settings
title: Michael Stapelbergs Website
email: your-email@domain.com
description: "Michael Stapelberg’s private website, containing articles about computers and programming, mostly focused on Linux."
baseurl: ""
url: "http://michael.stapelberg.de"

# Build settings
markdown: kramdown
permalink: "/Artikel/:title"
