baseURL = "https://michael.stapelberg.de/"
languageCode = "en-us"
title = "Michael Stapelbergs Website"
theme = "stapelberg"
disableKinds = ["RSS"]
publishDir = "docs"
ignoreFiles = ["\\.svgo\\.svg$", "turbopfor/Makefile$"]

[taxonomies]
tag = "tags"

[permalinks]
tags = "/posts/tags/:slug/"

[blackfriday]
  # Disable turning regular quotes into smart quotes (harmful for code blocks):
  smartypants = false

[params]
  description = "Michael Stapelberg’s private website, containing articles about computers and programming, mostly focused on Linux."

[mediaTypes."application/atom"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "feed"
isPlainText = false

[outputs]
home = [ "HTML", "Atom" ]
taxonomy = [ "HTML", "Atom" ]
